### ISSUE TITLE
updating userstyle wipes out custom domains

### ISSUE THREAD

**Issue by ashkitten** [dizzy-labs/dizzydon#9]

**Comment by dizzy-labs** [comment]
not sure how to fix this one tbh

**Comment by dizzy-labs** [comment]
Closing this because 4b4b78f10e3929ec62c344ad8149303db03f6235 removes the whitelist and just applies styles to any site with an element with id="mastodon".

Any changes will still be overwritten by updating the style, but I don't think that's avoidable with stylus.
